- name: Restart booksonic
  tags:
    - booksonic
  docker_container:
    name: booksonic-air
    image: linuxserver/booksonic-air
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
    volumes:
     - /home/josh/configs/booksonic:/config
     - /media/tv/media/Books/Audio\ Books/:/audiobooks
    published_ports:
     - 4040:4040
