- name: Restart a container
  when: ACTION=="refresh"
  docker_container:
    name: booksonic
    image: linuxserver/booksonic
    state: started
    pull: true
    restart: yes
    restart_policy: unless-stopped
    ports:
      - 4040:4040
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
    volumes:
     - /home/josh/configs/booksonic:/config
     - /media/tv/media/Books/Audio\ Books/:/audiobooks