# - name: Clear Folder before clone
#   file:
#     path: /media/c/configs/scripts/discord-bot
#     state: absent

- name: Update discord-bot code
  git:
    repo: https://gitlab.theflinners.com/joshfokis/discord-bot.git
    update: yes
    dest: /media/c/configs/scripts/discord-bot
    force: yes

- name: Restart a container
  docker_container:
    name: discordbot
    image: python:3
    state: started
    pull: true
    restart: yes
    restart_policy: unless-stopped
    env:
      APITOKEN: "{ APITOKEN }"
      DISCORDTOKEN: "{ DISCORDTOKEN }"
    volumes:
     - /media/c/configs/scripts/discord-bot:/code
    command: "bash /code/start.sh"