- name: Restart jackettbooks
  tags:
    - jackettbooks
  docker_container:
    name: jackettbooks
    image: linuxserver/jackett
    state: started
    restart: yes
    pull: yes
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
    volumes:
     - /media/c/configs/jackett_books:/config
     - /media/downloads/:/downloads/
    published_ports:
      - 9118:9118
