- name: Restart a container
  docker_container:
    name: lazylibrarian
    image: linuxserver/lazylibrarian
    state: started
    restart: yes
    pull: true
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
        DOCKER_MODS: "linuxserver/calibre-web:calibre"
    volumes:
     - /media/tv/media/Audio Books:/audiobooks
     - /media/tv/media/Books:/books
     - /media/tv/media/calibre:/calibre
     - /media/c/configs/lazylibrarian:/config
     - /media/downloads:/downloads