- name: Restart letsencrypt
  tags:
    - letsencrypt
  community.docker.docker_container:
    name: swag
    image: linuxserver/swag
    state: started
    restart: yes
    pull: true
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
        URL: "{{ URL }}"
        SUBDOMAINS: "{{ SUBDOMAINS }}"
    volumes:
     - /media/c/configs/letsencrypt:/config
    published_ports:
      - 80:80
      - 443:443
