- name: Restart ombi
  docker_container:
    name: ombi
    image: linuxserver/ombi:v4-preview
    state: started
    restart: yes
    pull: true
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
    volumes:
     - /media/c/config/ombi:/config
    published_ports:
      - 3579:3579