- name: Restart a container
  docker_container:
    name: openvpn-as
    image: linuxserver/openvpn-as:latest
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    ports:
     - "1194:1194" 
     - "943:943"
     - "9443:9443"
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
        
    volumes:
     - /home/josh/configs/openvpnas/:/config
