- name: Restart portainer
  tags:
    - portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
    volumes:
     - /media/c/configs/portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
    published_ports:
      - 9000:9000
