- name: Restart a container
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    pull: true
    restart: yes
    restart_policy: unless-stopped
    env:
        PGID: "1000"
        PUID: "1000"
    volumes:
     - /media/c/config/portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
    published_ports:
      - 9000:80