- name: Restart a container
  when: ACTION=="refresh"
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    state: started
    pull: true
    restart: yes
    restart_policy: unless-stopped
    network_mode: container:vpn
    env:
        PGID: "1000"
        PUID: "1000"
        TZ: "America/Chicago"
    volumes:
     - /media/c/config/sonarr:/config
     - /media/downloads/:/downloads/
     - /media/tv/media/TV:/tv
